### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Sanne1998HvA** [cmda-bt/pt-course-21-22#10]
# Package

## Class

Tech 1

## Repo link

](https://github.com/Sanne1998HvA/ProjectTech)

## Summary

Het gaat tot nu toe wel goed. Ik ben overal bij en heb wel een duidelijk beeld van wat ik wil gaan maken.
Zit nog te kijken welke functie ik wil gaan uitwerken maar ik kom er wel. Heb enkele jobstories om tussen
te kiezen dus heb wel wat ideeën.

## Any thoughts?

Ik denk dat ik tot nu toe wel op schema lig.

**Comment by Steinberg99** [comment]
Hey Sanne! Goed dat je een duidelijke richting hebt gekozen voor je concept. Ook extra leuk dat je er een probleem mee wilt oplossen die je zelf ervaart :) Probeer nog wel even een van je job stories te kiezen om een aantal concrete requirements te schrijven! 

Ook nog een kleine tip. Zet het `DS_store` bestand ook in je `.gitignore`. Deze heeft je applicatie namelijk niet nodig om te draaien :)
