### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by HanArchives** [cmda-bt/pt-course-21-22#122]
# Package

## Name

Han Ossef

## Class

Tech 5

## Repo link

[Link](https://github.com/HanArchives/bloktech)

## Summary

I started with brainstorming about all kinds of ideas. I landed on PawDoption. It's an app that lets you filter on your own preferences and find a dog that matches your preferences. I talked to friends that want to adopt dogs and that already own a dog for needs. I translated the need into requirements. After that I followed the tutorial. 

## Resources used

Friends and websites like: 
https://www.adopteereendier.be/honden

## Any thoughts?
The homework was nice. It teaches the basic CLI commends and I enjoyed the tutorial.

**Comment by KaivWezel** [comment]
Mooie Jobstory Han! Duidelijke richting voor jezelf en de flows zijn helder. Ze zijn nog niet zichtbaar in je wiki, check even of de link naar je bestand wel klopt, en zet de .DS_store files nog even in je gitignore-bestand. Deze bewaren enkel info die je finder op mac nodig heeft. Lekker doorgaan zo!

**Comment by HanArchives** [comment]
Hey! thanks voor de feedback! Het is mij gelukt om DS_Store in de .gitignore te zetten!
