### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by VanessaChoe** [cmda-bt/pt-course-21-22#124]
# Package

## Name

Vanessa Choe

## Class

Tech-5

## Repo link

https://github.com/VanessaChoe/Project-Tech

## Summary

Huiswerk voor week 1 gemaakt. Meer inzicht gekregen over welke feature ik wil gaan maken voor dit project en het gebruik van Github en Terminal. Onderzoek/huiswerk bijgehouden in Wiki.

## Resources used

App store: Tinder, Tourbar, TravelBuddy

## Any thoughts?

Wat vind je van de filter feature die ik wil gaan uitwerken? (Filteren op plaats/land - alfabetische volgorde, pre-selection, zoekbalk) - Meer info, zie wiki.

**Comment by KaivWezel** [comment]
Goed bezig, volgens mij heb je voor jezelf helder wat er in ieder geval in je project moet komen. Je wiki kan nog wel wat aandacht gebruiken. Check het voorbeeld van de [PT-repository](https://github.com/cmda-bt/pt-course-21-22/wiki). Voeg in ieder geval wat linkjes toe zodat de lezer sneller door het document heen kan. Succes!

[link naar titel](#title) = `[link naar titel](#title)`


# Title
