### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Chelsey-bommer** [cmda-bt/pt-course-21-22#125]
# Package

## Name

Chelsey Bommer

## Class

 Tech 5 

## Repo link

https://github.com/Chelsey-bommer/Matching-app

## Summary

 Ik heb de eerste concepten bedacht, en de eerste ervan uitgewerkt met de job stories en requirements. Ook heb ik alvast research gedaan naar de doelgroep.

## Resources used

 Ik heb de artikelen bij de verschillende pagina's staan.  

## Any thoughts?

 Was prima te doen.

**Comment by ivo-online** [comment]
Hi Chelsey, je hebt een leeg issue ingeleverd. De bedoeling is dat je onder de diverse kopjes iets vertelt over je eigen voortgang en aandachtspunten deze week.

**Comment by Chelsey-bommer** [comment]
Hi,

Ik zag dat ik per ongelijk alles als een comment heb laten staan. Ik zal
het zsm aanpassen

Op di 26 apr. 2022 11:19 schreef Ivo Nijhuis ***@***.***>:

**Comment by KaivWezel** [comment]
Hi Chelsey, lekker creatief aan het werk, leuke concepten! Huisgenootjes altijd welkom. Je repo lijkt nog niet helemaal up-to-date. De wireflow is nog niet zichtbaar in je wiki en ik zie ook geen mapje met afbeeldingen waar die vandaan kan komen. 
Readme is netjes, kijk of je van je `table of contents` nog linkjes kan maken.
