### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by thijew** [cmda-bt/pt-course-21-22#127]
# Package

## Name

Thije Wind

## Class

tech-5

## Repo link

https://github.com/thijew/blok-tech.git

## Summary

Ik heb mijn concept uitgewerkt.
Geoefend met de terminal
De artikelen gelezen.
## Resources used

De slides van week 1

## Any thoughts?

.

**Comment by KaivWezel** [comment]
He Thije, je repo is nog niet helemaal up-to-date denk ik of je hebt het heel druk. In elk geval, houd project-tech repo er lekker naast, dat scheelt je een hoop denk werk.
