### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by JonnaVisser** [cmda-bt/pt-course-21-22#129]
# Package

## Name

Jonna Visser--

## Class

 Tech-5 

## Repo link

https://github.com/JonnaVisser/MatchingApp-Dogs-At-The-Park 

## Summary

 Ik ga weer verder vanuit blok 3. Wil zeker weten dat ik dit blok alles goed begrijp en bij loop. Daarom dat ik in mijn wiki per week al mijn uitleg en het gemaakte werk bij ga houden. In week 1 project tech  in mijn wiki staat mijn gemaakt werk. 

## Resources used

terug te vinden in wiki

**Comment by KaivWezel** [comment]
Leuk idee Jonna! Wordt wel even een puzzel, maar dat vind je volgens mij niet erg. Gezien de feedback die je van Ivo hebt gekregen al goed verwerkt is laat ik je lekker verder werken.
