### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Romy-Thu** [cmda-bt/pt-course-21-22#13]
# Package

## Name

Romy-thu Zwijnenburg

## Class

Tech2

## Repo link

https://github.com/Romy-Thu/Blok-Tech_klas-tech2

## Summary

Deze week heb ik vooral gekeken naar hoe de terminal werkt en github. Ik heb veel vragen gesteld aan verschillende docenten en samen gezeten met mijn klasgenoten. we hebben elkaar geholpen en vullen elkaar aan. Verder heb ik ook gezeten aan mijn concept en 5 jobstories met requirments

## Resources used
https://www.youtube.com/watch?v=5HQzn_KDJCY 
https://www.youtube.com/watch?v=qn6HmSJVDgM
https://changelog.com/posts/install-node-js-with-homebrew-on-os-x 

## Any thoughts?

in het begin vond ik dit blok erg moeilijk, je wordt vol gegooit met informatie waardoor je een beetje stress krijgt. ik heb zelf heel weinig verstand van back-end en dat vond ik aardig pittig. Maar de docenten zijn erg hulpvol en staan klaar om je te helpen

**Comment by ivo-online** [comment]
Fijn dat je op weg bent, en blijf vooral vragen stellen! Ik zie op je wiki dat je ook lekker bent opgeschoten met het uitwerken van je concept en job story.
