### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by eliran075** [cmda-bt/pt-course-21-22#132]
# Package

## Name

Eliran Abohadana

## Class

tech-5

## Repo link

https://github.com/eliran075/bloktech

## Summary

Conceptualiseren

## Resources used

Biggym app en tinder als inspiratie

## Any thoughts?

Nog geen op het moment

**Comment by SamSlotemaker** [comment]
lukt het ook om dingen naar github te pushen? Laat het vooral weten wanneer je vragen hebt of ergens niet uitkomt.
