### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by HanArchives** [cmda-bt/pt-course-21-22#134]
# Package

## Name

Han

## Class

Tech 5

## Repo link

https://github.com/HanArchives/bloktech/wiki

## Summary

Begonnen met html en css. Heb ook alle feedback verwerkt en mijn wiki is als goed is nu in orde. Ik wil nog graag research doen naar template engines en graag nog mijn doelgroep interviewen. 

## Any thoughts?
Ik weet nog niet precies hoe ik mijn afbeeldingen in mijn wiki tevoorschijn krijg.

**Comment by KaivWezel** [comment]
Afbeeldingen kan je in je repo zetten om ze zichtbaar te maken. Stel je kattenafbeelding; `/static/img/cat.jpg`. Je kan dit pad nu gebruiken in je readme om afbeeldingen te laten zien met `![kattenafbeelding](/static/img/cat.jpg)`

```
├── static
           ├── img
           |    └── cat.jpg
           ├── html
           └── css
├── views
├── server.js
└── readme.md

```

Verder een mooie iteratie over je schermen, ik denk dat het goed is om de voorkeuren in stappen op te delen. Goed bezig dus!

**Comment by HanArchives** [comment]
Hey Kai! Thanks! Ik heb het nu verandert maar het lukt mij nog steeds niet..

**Comment by KaivWezel** [comment]
Als ik de schetsen van mijn eigen Bloktech wiki er even bij pak (https://github.com/KaivWezel/Bloktech/blob/master/img/htmlcssjs.png).
Als je hierop klikt kom je als het goed is op github op mijn schetsen. Met dezelfde link zou je in je wiki dan de afbeelding kunnen laten zien als `![alt-text](link naar img)`. Als dat nog niet lukt na de vakantie maar even vragen dan zou ik het vanaf hier ook niet direct kunnen zien.
