### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by Chelsey-bommer** [cmda-bt/pt-course-21-22#138]
# Package

## Name

Chelsey Bommer

## Class

Tech 5

## Repo link

[Chelsey repo ](https://github.com/Chelsey-bommer/Matching-app)

## Summary

Ik heb een basis voor mijn readme opgezet. Ook heb ik veel in mijn wiki gezet qua research, ook over mijn git strategie. Ik ben ook begonnen met het bouwen van mijn site. Ik heb een basis van html, CSS en javascript nu. Er moet nog wel meer gebeuren qua vormgeving van de site en meer met de interaction en states. 

## Resources used

Mijn links voor resources staan bij de research zelf, in mijn wiki. 

## Any thoughts?

Huiswerk van dit vak was prima te doen deze week.

**Comment by SamSlotemaker** [comment]
Ziet er al goed uit.
Deze laatste 3 regels zijn in theorie overbodig tho, aangezien bijvoorbeeld je css in je static folder staat, wordt deze automatisch mee geserveerd. Je zou het uiteraard wel zo kunnen laten als je dit duidelijker vindt en makkelijker in gebruik ;) 
```js
app.use("/static", express.static('./static/'));
app.use('/css', express.static('./static/css'));
app.use('/img', express.static('./static/img'));
app.use('/js', express.static('./static/js'));
```
