### ISSUE TITLE
Week 3

### ISSUE THREAD

**Issue by hicham-sahla** [cmda-bt/pt-course-21-22#144]
# Package

## Name

Hicham Sahla
## Class

Tech-4
## Repo link

https://github.com/hicham-sahla/blok-tech-feature

## Summary

Ik heb deze week onderzoek gedaan naar de beste code formatters. Zo heb ik de keuze gemaakt om ESlint te gebruiken om dat dit makkelijk integreert met VS code en ook een optie heeft om EJS te formatten. Buiten dat om heeft deze formatter meer dan 20 miljoen downloads. Dat zegt waarschijnlijk ook wel genoeg
## Resources used

https://livecodestream.dev/post/best-vscode-extensions-for-javascript/#:~:text=Prettier&text=Prettier%20is%20an%20opinionated%20code,keywords%20for%20more%20readable%20code.

## Any thoughts?

Ik was deze week afwezig maar heb genoeg doorgewerkt buiten de school uren om. Zo ben ik begonnen met kijken naar een compiler als gulp om SCSS en JS te minifyen en compilen. Ik heb dit vooralsnog nog niet helemaal werkend gekregen. Denk wel dat ik er bijna ben.

**Comment by Chazzers** [comment]
Hi Hicham, je bent lekker op weg. Goed om te zien dat je met eslint aan de slag bent gegaan. Zoals je zegt is het een tool die veel gebruikt wordt. Ook top dat je met de MVC structuur aan de slag bent gegaan. Hiermee loop je al een beetje voor op het team onderdeel straks. Als je met gulp nog vast loopt heb kan ik je daarbij helpen. Heb dit kortgeleden ook nog gedaan dus ben er bekend mee. Trek verder aan de bel als je nog vragen heb en nog veel succes!
