### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by sharonvopzeeland** [cmda-bt/pt-course-21-22#15]
# Package

## Name

Sharon

## Class

Tech-3

## Repo link

https://github.com/sharonvopzeeland/blok_tech.git 

## Summary

Octocat artikelen gelezen en opdrachten gedaan, terminal artikelen gelezen en tutorial gedaan. Verder gewerkt aan concept

## Resources used

Alles gevonden op de Github, vraag gesteld op Teams en zelf wat informatie gevonden voor de terminal tutorial op stackflow

## Any thoughts?

Toen ik wilde pushen van de run folder uit de tutorial, gaf die aan dat dat niet kon. Ook toen ik gewoon mijn folder voor dit vak wilde pushen was het niet meer geconnect aan mijn personal token, geen idee hoe ik dat kan oplossen of de volgende keer beter doen. Ook dacht ik dat je bij de tutorial meer het antwoord zegmaar kreeg, de codes die je moest/kon gebruiken. Maar de tutorial met de terminal was wel erg handig!

**Comment by samanthavz** [comment]
Hi Sharon!

Je bent zeker niet de enige die problemen heeft met de terminal. Als je tegen een issue aanloopt kan je een screenshot van de errors in teams gooien, dan zullen wij je helpen!

Ik snap dat het handig is als je hints zou krijgen naar het antwoord ;), maar ik hoop dat je het nu wel goed begrijpt. Je zou altijd nog een cheatsheet erbij kunnen houden met de mogelijke commando's, maar het is natuurlijk nog beter als je dit uiteindelijk een beetje uit je hoofd weet (zeker niet alle commando's hoor, maar die je het meest zult gebruiken zoals ```cd``` en ```ls``` bijvoorbeeld).

Ik zie nog niks in je wiki, dus probeer hier deze week al wat aan toe te voegen. Daarnaast heb je wel al een ```.gitignore``` aangemaakt, maar waarschijnlijk heb je hiervoor al je ```DS_Store``` gespushed. Deze mag je weghalen!

Je bent goed op weg, ga zo door :)

**Comment by sharonvopzeeland** [comment]
Hey!

Dit mailtje is mij even helemaal ontgaan, sorry! Bedankt voor je mail in ieder geval en klopt, heb teams inderdaad gebruikt en met alleen hints leer je ook niks ;) Ik ga zorgen dat ik mijn wiki meer up to date ga houden, alles overviel me even van hoe lastig het is! Maar gaat goed komen.

Groetjes, Sharon Tech-3
