### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by annekesteller** [cmda-bt/pt-course-21-22#18]
# Package

## Name

Anneke Steller

## Class

tech2 

## Repo link

https://github.com/annekesteller/bloktech
## Summary

Deze week hebben we vooral een introductie gehad over het vak en de terminal. Ik heb verschillende artikelen gelezen  en video's die op github stonden. Deze tutorials hebben mij heel erg geholpen om alles wat beter te begrijpen. Verder hebben we al nagedacht wat voor feature we willen gaan bouwen voor de komende 5 weken. 

code van de tutorial:  YW5uZWtlc3RlbGxlcgo=

## Resources used

https://askubuntu.com/questions/1030099/how-to-print-text-in-the-terminal-as-if-its-being-typed

https://www.howtogeek.com/278599/how-to-combine-text-files-using-the-cat-command-in-linux/

## Any thoughts?

In het begin van de week was ik wel even in paniek omdat ik er echt niks van snapte. Maar na deze oefeningen snap ik het al wat beter dus ze hebben mij wel heel erg geholpen.

**Comment by ivo-online** [comment]
Fijn dat je over de eerste schrik heen bent en vergeet niet dat we er zijn om te helpen! Een goede volgende stap is om in je wiki ook info over je concept en job stories toe te voegen, zodat we helder krijgen wat je de komende weken gaat bouwen.
