### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Marley020** [cmda-bt/pt-course-21-22#19]
# Package

## Name

Marleen Bonhof

## Class

Tech-1

## Repo link

https://github.com/Marley020/Blok-Tech

## Summary

I've downloaded a package called express, since we're going to be working with this one to set up our server. I've followed a course, about a year ago from Andrew Mead and learned the basics of es6 and node. I came to understand that express is a package which simplifies the standard http module from node. I have set up a base server that listens to port 1337 with two routes namely the root: '/', and the about page: '/about'.

## Resources used

I've read the documentation of express.js and also followed the course of Andrew Mead, besides that I've watched numerous YouTube videos and read some medium articles.

**Comment by SamSlotemaker** [comment]
Lekker bezig! wellicht dat de DS Store bestanden ook nog handig zijn in je gitignore, deze zijn niet zo relevant voor anderen :)
