### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by MichaelWilhelm1** [cmda-bt/pt-course-21-22#25]
# Package

## Name

Michael Wilhelm

## Class

Tech-3

## Repo link

https://github.com/MichaelWilhelm1/Tech-Blok

## Summary

Ik heb in mijn wiki mijn concept voor een functie beschreven, job stories, requirement list en wireflow gemaakt.

## Resources used

GitHub

**Comment by samanthavz** [comment]
Hi Michael!

Je repo ziet er erg netjes uit, je bent goed op weg. Ik zie ook dat je al je wiki hebt aangevuld. Wel zou ik zeggen dat de job stories en requirements list een beetje moeilijk te lezen is. Zo zou je het in een bulleted list kunnen zetten voor overzichtelijkheid :)

Je zou je ook nog een beetje kunnen verdiepen in je doelgroep. Zo zou je kunnen onderzoeken waar vakantiegangers tegen aanlopen en hoe je daar een oplossing voor kan bieden. Misschien bestaan er al soortgelijke apps waar je inspiratie uit kan halen?

Ga zo door!
