### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by DennisHvA** [cmda-bt/pt-course-21-22#28]
# Package

## Name

Dennis de Graaf

## Class

Klas 1 

## Repo link

[https://github.com/DennisHvA/Blok-tech](https://github.com/DennisHvA/Blok-tech)

## Summary

Ik heb nagedacht over de matching app. Een keuze gemaakt, feature gekozen, job stories gemaakt en een requirementslist. Verder ben ik handiger geworden in de terminal. Ik heb hiermee ook git geïnstalleerd en gekoppeld aan mijn GitHub. Ik heb de wiki template gecloned, alleen krijg ik deze nog niet terug in de repository in GitHub.

## Resources used

Gitdocs

## Any thoughts?

Ik vond het fijn dat het huiswerk nog niet veel was, omdat het nog best lastig is om te werken met de terminal.

**Comment by SamSlotemaker** [comment]
Kijk nog eventjes goed naar een .gitignore, want bepaalde dingen wil je niet naar github pushen. Node_modules in dit geval bijvoorbeeld, aangezien deze enorm groot kan worden en deze niet nodig is voor anderen die jouw project willen gebruiken. 
Als de .gitignore in orde is kun je 'm ook nog even proberen te verwijderen van je github, wellicht dat dit kan helpen: https://techstacker.com/remove-node_modules-after-adding-gitignore/
