### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by PipHarsveld** [cmda-bt/pt-course-21-22#29]
# Package

## Name

Pip Harsveld

## Class

Klas tech 2

## Repo link

[https://github.com/PipHarsveld/projectTech](url)

## Summary

Ik heb deze eerste week nagedacht over welk concept en welke functie ik wil gaan uitwerken. Ook heb ik erg veel geoefend met de terminal, CLI en git, ik snapte hier in het begin echt helemaal niets van, maar na alle artikelen en bronnen te lezen die bij deze week horen ging het al wat beter. Ik heb tot nu toe dus vooral dingen gedownload via de terminal, geoefend met de basiscommands en mijn github en wiki ingericht.

## Resources used

Ik heb de bronnen die bij deze week en de huiswerkopgaves stonden gelezen, daarbuiten nog niet echt veel resources gebruikt.

## Any thoughts?

Ik vond deze eerste week meteen al erg pittig. Tijdens de lessen ging alle informatie erg snel en kon ik het lastig volgen, ik heb toen hulp gehad van medestudenten waardoor het wel redelijk ging. Pas toen ik later thuis op een rustig moment door alle artikelen en bronnen heen ging spitten, begon alles wat in de lessen was uitgelegd een beetje duidelijker te worden.
Het is mij deze week alleen nog niet gelukt om de CLI interactive tutorial te volgen, omdat ik foutmeldingen kreeg. Ik heb dit in het teamskanaal geplaatst en wacht op dit moment nog op antwoord.

**Comment by ivo-online** [comment]
Is het intussen gelukt met de CLI tutorial?
