### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by sasjakoning** [cmda-bt/pt-course-21-22#34]
## Name
Sasja Koning

## Class
Tech-2

## Repo link
https://github.com/sasjakoning/blok-tech-2022/tree/development

## Summary
This week I started work on creating a matching app. I decided to go with something that involves gamification. The specific feature I'll be doing probably wont use it but it would be a cool thing to add if I manage to have spare time.

I made job stories:
![Job stories - requirements list](https://user-images.githubusercontent.com/13648845/153771500-5b2e8ea7-03b2-44f1-a5eb-614b10486850.png)

Thought out a concept:
![Concept](https://user-images.githubusercontent.com/13648845/153771516-16783ac1-a170-4453-923e-a015f33b612f.png)

And did some research:
![Benchmark creation](https://user-images.githubusercontent.com/13648845/153771642-ebb93526-f74f-494b-81b9-d16ef4aac8c4.png)

I also made several sketches and came up with a wireframe(ish):
![iPhone 8 - 1](https://user-images.githubusercontent.com/13648845/153771554-3b0df7a3-6a2c-42d6-a89f-67fafe616031.png)

I created a seperate branch to start work on the base html/css and made some branches to mess around with Node.js, npm, Express and mongoDB. Also did some reading about AJAX and such.

Thats about all the tryhard stuff I'll be doing this week.

### For Backend
Played around with node.js and npm. Installed Nodemon and Express. I had some trouble understanding what I was doing so I removed my development branch and started over. I read some docs on npm and node.js which made things a little easier. I'll have to actually make stuff with it to fully understand it, though.

## Resources used
https://docs.npmjs.com/
https://nodejs.org/en/docs/guides/
https://github.com/cmda-bt/be-course-21-22/

## Any thoughts?
(for Backend)
The assignments were a little confusing. Right at the first step I was already thinking "uhh... what?" even though I'm very excited to start working on backend. I can understand the idea of letting students figure it out themselves but doing so during the very first lesson is perhaps a little overboard.

In the future I'm excited to start working on Express and getting a website to actually run on it.

**Comment by ivo-online** [comment]
Hi Sasja, dank voor je lekker uitgebreide update. Ik  zie dat je veel op papier hebt gezet m.b.t. de feature die je gaat bouwen. Hopelijk staat dit ook allemaal in je wiki (die ga ik straks nog bekijken) en dan zou je in je issue ook mogen volstaan met een verwijzing daar naartoe. Scheelt je hopelijk weer wat werk :)
