### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by YaraPrins** [cmda-bt/pt-course-21-22#37]
# Package

## Name
Yara Prins

## Class
Tech 3

## Repo link
https://github.com/YaraPrins/blok-tech.git

## Summary
I made a requirement list, wireframes and the flow for my wireframes.
I also deleted my test.txt files in my subfolders, per the tip of Victor Boucher (to keep my repo clean and organized)
Lastly I did some research and reading, but have not yet put the research in my own words on my wiki. Working on it though!

**Comment by samanthavz** [comment]
Hee Yara!

Je repo ziet er zeker netjes uit (goede tip van Victor). Ook zie je dat je je readme een beetje hebt aangevuld, ga zeker ook zo door. Je app hoeft niet per se in een apart mapje, dus als je het handig vind kan je dat nog aanpassen.

Goed om te horen dat je begonnen bent met je research, probeer dit dus ook volgende week toe te voegen aan je wiki. Ik zie dat je een pdf in je repo hebt staan met je voortgang, dit zou je allemaal kunnen verplaatsen naar je wiki! Dit ziet er allemaal heel georganiseerd en overzichtelijk uit, dus ga zeker zo door.
