### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by rvd98** [cmda-bt/pt-course-21-22#42]
# Package

## Name

Rick van Dijken

## Class

Tech-1

## Repo link

https://github.com/rvd98/tech-repo-rick

## Summary

Job stories, requirement list, doelgroep gedefinieerd en een wireframe gemaakt van 'likes' terugvinden.

## Resources used

Github

## Any thoughts?

Ik zat vrij lang vast met git waar volgensmij niet de prioriteit lag.

**Comment by SamSlotemaker** [comment]
Git is ongekend handig om te beheersen en eigenlijk een must om te begrijpen als developer, dus het is helemaal niet erg als je daar iets langer mee bezig was. Ik hoop dat het nu iets duidelijker is, en voel je anders vrij om me even een berichtje te sturen wanneer je wat extra uitleg wilt!
