### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Zephelion** [cmda-bt/pt-course-21-22#43]
# Package

## Name

Russell Numo

## Class

Tech - 1

## Repo link

https://github.com/Zephelion/Project-Tech

## Summary

Made the job stories and requirement list

## Resources used

Knowledge

## Any thoughts?

Nothing was particularly hard

**Comment by SamSlotemaker** [comment]
Lekker bezig. Je zou wellicht nog kunnen kijken of je packages als nodemon als Dev Dependency kan installeren, deze zijn namelijk niet nodig in productie maar 'handig' tijdens het developen.
