### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by cheunyinz** [cmda-bt/pt-course-21-22#46]
# Package

## Name

Cheun Yin Zhang

## Class

Tech 3

## Repo link

https://github.com/cheunyinz/pt_matching_app

## Summary

Deze week kon ik niet de lessen volgen waardoor veel heb gemist. Ik heb wel gekeken naar BE en met json gewerkt etc. Daarnaast probeerde ik ook mijn concept te bedenken maar dat was niet gemakkelijk omdat ik niet precies begreep wat voor concept het moest zijn. Hetzelfde geld voor feature.

## Resources used

Ik heb de slides gebruikt

## Any thoughts?

Het was even wennen om alles via Github te doen dan DLO. Het was beetje abstract wat ik moest doen maar met wat research was het toch deels gelukt

**Comment by samanthavz** [comment]
Hi Cheun!

Ik snap dat het lastig is om zomaar een concept te bedenken, je zou altijd bij de issues van medestudenten kunnen kijken om te zien hoe zij het hebben aangepakt. Het is de bedoeling dat je een feature gaat uitwerken voor een matching app. En je bent er vrij in om te kiezen wat voor matching app het gaat zijn, denk aan huisdieren matchen met baasjes, mensen matchen met dezelfde interesses of misschien wel een kamerplant matchen met een woonkamer? Het kan echt van alles zijn ;)

Je github ziet er verder netjes uit, probeer misschien alvast een begin te maken aan je wiki.

Als je vragen hebt over van alles kan je mij of Victor altijd een berichtje sturen op teams of in de teams groep van blok tech!
