### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by Michiel1998** [cmda-bt/pt-course-21-22#54]
# Package

## Name

 Michiel Schipper

## Repo link

https://github.com/Michiel1998/Blok-Tech

## Summary

De eerste pagina met html css en js. zero state, login, ontdek pagina

**Comment by samanthavz** [comment]
Hey Michiel,

Probeer nog wat progressie te maken bij je wiki! Ik zie dat er al wat informatie bij staat, maar nog niet onder bepaalde tabs en er mag zeker nog wat bij (denk aan meer info over je templating engine, linters, text editor, command line etc). Ik denk ook dat je je readme nog wat kan aanpassen door te kijken naar readme's van andere repo's en te zien welke informatie zij er in hebben staan. 

Je repo ziet er goed uit en ik zie dat je al goed op weg bent met het bouwen van je website. De volgende stap is om een templating engine te gaan gebruiken. Deze templating engine files kan je allemaal in je ```views``` mapje gooien. Dingen zoals styles, images en scripts kunnen dan bijvoorbeeld in je ```public``` mapje.

Ik zou ook nog je ```DS_store``` uit je repo verwijderen en in je ```.gitignore``` plaatsen!

Veel succes! 😄
