### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Laserjonge** [cmda-bt/pt-course-21-22#62]
# Package

## Name

Axel de Ruiter

## Class

TEC1

## Repo link

[https://github.com/Laserjonge/Blok-Tech]()

## Summary

I have made some ideas about the concept and decided to focus on matching driving instructors with students and vice versa.

## Resources used

The theory from this course and I searched for competitors on the internet.

## Any thoughts?

So far it's hard for me to follow every step, it takes longer because every resource online is in English. But overal I'm trying my best to do all the assignments.

**Comment by Steinberg99** [comment]
Origineel concept! Leuk dat je iets wilt maken waarmee mensen beter een passende rijinstructeur kunnen vinden. Probeer je concept nog wel iets meer in detail toe te lichten.  Job stories, requirements en design zien er ook goed uit!
