### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by romyjkk** [cmda-bt/pt-course-21-22#63]
# Package

## Name

Romy Jongkees

## Class

Tech-204

## Repo link

https://github.com/romyjkk/bloktech

## Summary

Ik heb de artikels uit het huiswerk gelezen.

## Resources used

Artikels uit het huiswerk

## Any thoughts?

Alles is nog erg vaag voor me en ik kan niet zeggen dat ik heel veel van de terminal en Git snap. Hoe kom ik bij mijn Github in mijn terminal?

**Comment by ivo-online** [comment]
Lukt het intussen met GitHub en de terminal? Als er nog problemen mee zijn, zou het ideaal zijn er in de les even naar te kijken morgen.
