### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Bram-ter** [cmda-bt/pt-course-21-22#7]
# Package

## Name

Bram Tersteeg

## Class

Tech 3

## Repo link

https://github.com/Bram-ter/blok-tech

## Summary

Ik vond het in het begin moeilijk om ideeen te verzinnen voor een matching app. Ik ben tot nu toe ook niet echt super tevreden over mijn ideeen. Ik heb er uiteindelijk toch maar 1 gekozen om job stories van te maken. Misschien komt er nog een idee opdrijven komende weken.

## Resources used

Ik heb voor ideegeneratie op deze website gekeken https://medium.com/flutter-community/12-top-mobile-app-development-ideas-that-can-change-the-world-in-2020-598cb995834e

## Any thoughts?

Aangezien ik de les had gemist kan ik niet zo veel zeggen over de les. Verder vond ik de opdracht wel duidelijk en was hier genoeg over terug te vinden in github.

**Comment by samanthavz** [comment]
Hi Bram! Zomaar een idee verzinnen kan inderdaad lastig zijn, bij mij helpt het altijd om even bij de rest te kijken (door bijvoorbeeld door de issues te bladeren van anderen). Zo kan je ook veel inspiratie opdoen :)

Ik zie nog niet veel bij je wiki, dus probeer daar nog wat aan toe te voegen. De linkjes in de wiki linken nu nog naar de repo van project-tech. Je hebt wel al een ``` .gitignore``` aangemaakt met ```node_modules``` erin, goed bezig!

Je zou eventueel nog alle images in je repo in een apart mapje zetten voor overzichtelijkheid.
