### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by PipHarsveld** [cmda-bt/pt-course-21-22#70]
# Package

## Name

Pip

## Class

Tech 2

## Repo link

https://github.com/PipHarsveld/projectTech

## Summary

Afgelopen week heb ik onderzoek gedaan naar hoe je markdown kan schrijven, welke git strategies ik kan gaan gebruiken, version control en hoe je het beste git commit messages kan schrijven. Een paar van deze onderzoeken moet ik nog wel gaan vastleggen in mijn wiki. Verder ben ik begonnen met het maken van mijn HTML pagina's en CSS. Ik ben hier helaas niet zo ver mee als dat ik wilde zijn maar ik ga daar aankomende week weer mee verder.

## Resources used

Alle bronnen die in de lessen worden aangeboden + die in mijn wiki staan bij resources. 

## Any thoughts?

Voor project tech ben ik afgelopen week geen grote problemen tegen gekomen. De opdrachten waren vooral onderzoeken doen, maar dat hoort er ook bij.

**Comment by sjagoori** [comment]
Je bent lekker op weg, Pip!
