### ISSUE TITLE
Week 3

### ISSUE THREAD

**Issue by Marengd** [cmda-bt/pt-course-21-22#78]
# Package

## Name

Danian Marengo

## Class

Tech ― 3

## Repo link

https://github.com/Marengd/pt-matching-app-21-22

## Summary

Ondanks ik nog het een en ander moet aanvullen heb ik het proces uit mijn readme overgezet in mijn Wiki. Daarnaast ben ik aan de slag gegaan met het uitwerken van mijn wireframes in HTML en CSS door middel van de template engine Ejs.

## Resources used

https://www.youtube.com/watch?v=lYVKbAn5Od0

## Any thoughts?

Het werken met Ejs was vooral een kwestie van wennen, wat het hier en daar lastig maakte om mee te werken.

**Comment by samanthavz** [comment]
Hey Danian,

Ik snap zeker dat het wennen is om opeens met een templating engine te werken. Als tip kan ik je geven om vooral de documentatie van EJS te bestuderen. Uiteindelijk kunnen templating engines je veel tijd besparen namelijk!

Je repo ziet er mooi uit, probeer nog zo veel mogelijk progressie te maken met het schrijven van code voor de voortgangsgesprekken. Je readme bestaat nu uit een samenvatting van weken, maar je zou hier eigenlijk in willen hebben wat dit voor een app is (het concept), hoe je het installeert, door wie en met wat het gemaakt is etc. 

Probeer ook alle tabs onder **configuration** in je **wiki** nog in te vullen, dit zal je veel stress besparen aan het einde ;)
