### ISSUE TITLE
Week 3

### ISSUE THREAD

**Issue by cheunyinz** [cmda-bt/pt-course-21-22#80]
# Package

## Name

Cheun Yin

## Class

Tech 3

## Repo link

https://github.com/cheunyinz/pt_matching_app

## Summary

Ik ben in week drie begonnen met de mark-up van de pagina's op basis van mijn wireframes en heb ik ook wat custom properties gedeclareerd. Ik heb ook de stylelinter gedownload in combinatie met prettier.

## Resources used

https://stylelint.io/user-guide/get-started
https://www.youtube.com/channel/UCvXscyQ0cLzPZeNOeXI45Sw
https://www.youtube.com/watch?v=tb7081fzfdE

**Comment by samanthavz** [comment]
Hi Cheun!

Je bent al goed op weg met je app, probeer het nog zo veel mogelijk op te vullen. Je wiki is nog behoorlijk leeg, ik zou daar deze week wat aandacht aan besteden. De pages die je hebt zijn nog best mager dus er kan nog wel wat informatie bij! Word hier zeker niet door ontmoedigd hoor, de focus moet natuurlijk ook op je app zelf liggen maar om wat stress aan het einde te besparen zou ik proberen je wiki wekelijks bij houden. (Ik zie trouwens dat een link naar een afbeelding nog niet helemaal goed gaat in **design**).

Als tip zou ik naar readme's van grote repo's bekijken en daar wat inspiratie uit halen. Je hebt nu een wekelijkse samenvatting er in staan, wat je dus eigenlijk wil is een samenvatting van je app, hoe het is gemaakt en hoe iemand je app kan installeren en bekijken etc.
