### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by MegandeRuig** [cmda-bt/pt-course-21-22#85]
# Package

## Name

Megan de Ruig

## Class

Tech 2

## Repo link

https://github.com/MegandeRuig/Project-Tech

## Summary

Tijdens week 2 heb ik de basis van de read.me opgezet met hierin een inleiding, installation guide voor het project en een license. Verder heb ik mijn documentatie bijgewerkt met onder andere research naar de text-editor en een github strategy. Ook heb ik alle schermen in html en css gezet.

## Resources used

Git commit message: https://gist.github.com/lisawolderiksen/a7b99d94c92c6671181611be1641c733

Best free text editors: https://www.lifewire.com/best-free-text-editors-4155819

## Any thoughts?

Het was tijdens het schrijven van de documentatie erg fijn dat er voorbeelden van vorige jaren te vinden waren op Github zodat ik wat richtlijnen had!

**Comment by sjagoori** [comment]
Lekker bezig Megan! Vergeet je niet om je readme aan te vullen?
