### ISSUE TITLE
Week 3

### ISSUE THREAD

**Issue by Bram-ter** [cmda-bt/pt-course-21-22#86]
# Package

## Name

Bram Tersteeg

## Class

Tech 3

## Repo link

https://github.com/Bram-ter/blok-tech

## Summary

Deze week heb ik een beetje om me heen gekeken gepraat met docenten, hierdoor heb ik een beter idee gekregen van wat voor concept ik nou precies wilde maken. Ook heb ik hierbij ejs, en een paar apis bekeken. Mijn folder structuur heb ik ook veranderd zodat dingen zoals mijn css en ejs pagina's geladen zouden worden door mijn server.js. Hierbij heb ik ook een .stylelintrc.json gemaakt maar verder nog niet getest.

## Resources used

https://stylelint.io/user-guide/get-started
https://leafletjs.com/SlavaUkraini/
http://bl.ocks.org/phil-pedruco/7745589

**Comment by samanthavz** [comment]
Hi Bram,

Je repo ziet er goed opgeruimd uit! Ook goed bezig met je templating engine, blijf zoveel mogelijk hier nog aan doorwerken de aankomende weken :)

Je readme is goed op weg maar kan zeker nog wat aanvullen gebruiken. Ook je wiki kan bij het **configuration** deel nog veel aanvulling gebruiken. Probeer dit ook elke week bij te houden. Voor week 3 zou je je dus nog goed kunnen verdiepen in linters, CLI, text editor themes, build tools etc. Ga bijvoorbeeld (tenzij je dit al gedaan hebt natuurlijk) hier en daar wat extentions downloaden voor je code editor en kijk wat ze allemaal doen! Zo zou je wat handige tricks kunnen vinden om alles wat makkelijker/leuker te maken. (Ik heb bijvoorbeeld ooit een top 10 lijst opgezocht en alles uitgeprobeerd).

Keep it up!
