### ISSUE TITLE
Week 3

### ISSUE THREAD

**Issue by evaboogaard** [cmda-bt/pt-course-21-22#89]
# Package

## Name
Eva Boogaard

## Class
tech-2

## Repo link
https://github.com/evaboogaard/blok-tech

## Summary
Ik heb aan mijn wiki gewerkt, mijn readme opgezet & mijn concept versimpeld. Ook heeft Ivo me weer hoop gegeven voor het blok, want ik zag t allemaal even niet meer zitten. 

## Resources used
https://css-tricks.com/form-validation-ux-html-css/
https://stackoverflow.com/questions/7410063/how-can-i-listen-to-the-form-submit-event-in-javascript
https://www.w3schools.com/jsref/event_preventdefault.asp
https://www.slant.co/versus/8627/8628/~jshint_vs_eslint
https://stackoverflow.com/questions/4295782/how-to-process-post-data-in-node-js
https://futurestud.io/tutorials/npm-how-to-run-eslint-fix-from-npm-script
https://codeforgeek.com/handle-get-post-request-express-4/
https://stackoverflow.com/questions/24800511/express-js-form-data
https://www.cognitoforms.com/blog/106/css-tips-and-tricks-for-customizing-error-messages

## Any thoughts?
Er wordt goed polshoogte gehouden bij de studenten en we kunnen altijd terecht bij iemand met onze vragen, wat door mij en waarschijnlijk vele anderen erg gewaardeerd wordt. :)

**Comment by sjagoori** [comment]
Je bent goed op weg, Eva, geef de hoop niet op!
