### ISSUE TITLE
Week 3

### ISSUE THREAD

**Issue by sharonvopzeeland** [cmda-bt/pt-course-21-22#92]
# Package

## Name

Sharon van Opzeeland

## Class

Tech-3

## Repo link

https://github.com/sharonvopzeeland/blok_tech 

## Summary

Nieuwe kleurenschema aangemaakt en verder gecodeerd, deze keer met template engine. Nog even meer uitzoeken over Linting met ESLint en dan ben ik weer op schema

## Resources used

Github, tutorial van Raddy (https://www.youtube.com/watch?v=A01KtJTv1oc&t=1s) om zo template engine EJS te snappen

## Any thoughts?

Super fijn om even een voortgangsgesprekje te hebben en een middagje om vragen te stellen terwijl je aan je code werkt!

**Comment by samanthavz** [comment]
Hee Sharon!

Je bent goed bezig hoor, templating engines zijn natuurlijk helemaal nieuw dus dan is het even wennen. Als je iets niet meer weet kan je altijd de documentatie van EJS opzoeken, daar staat ook altijd veel in :)

Je readme is verder nog best leeg, probeer dat nog wat aan te vullen met bijvoorbeeld how to install, built with, credits, bronnen, een leuke banner etc.

Ook je wiki kan nog echt wat aanvulling gebruiken, probeer het ook aan te vullen met wat plaatjes zoals wireframes, designs, code etc. Je kan ook vergelijken (denk aan 2 linters vergelijken en onderbouwen waarom je de een kiest). Je verwijst ook hier een daar naar onderwerpen waar je mee bezig bent geweest (bijv wireframes) dus laat dit ook echt zien in je wiki!

Je bent goed op weg dus blijf doorbouwen aan je app ;)
