### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by YaraPrins** [cmda-bt/pt-course-21-22#93]
# Package

## Name
Yara Prins

## Class
Tech 3

## Repo link

https://github.com/YaraPrins/blok-tech

## Summary

Ik heb mijn wiki en mijn README.md geupdate, de videos van Wes Bos bekeken en nog een andere video over markdown. Ik probeer nu zelf ook steeds meer (juiste) markdown te gebruiken in mijn readme bijvoorbeeld, zodat het echt in mijn systeem komt hoe ik bijvoorbeeld een afbeelding in moet voegen.

Ik vind markdown zelf een vrij simpele en voor de hand liggende taal om te leren, dus ik pikte het ook snel op.

Ik ben alleen helaas nog niet toe gekomen aan het maken van de HTML paginas van mijn feature (ik loop helaas door privé omstandigheden wat achter..)

## Resources used

- [De videos van Wes Bos](https://youtube.com/playlist?list=PLu8EoSxDXHP7v7K5nZSMo9XWidbJ_Bns3)
- [Video van James Bachini](https://youtu.be/qhoXn4bIE1s)

**Comment by samanthavz** [comment]
Hi Yara!

Vervelend dat je wat achter loopt. Je kan jezelf goed verdiepen jouw gekozen templating engine, dit gaat je veel tijd besparen als je hier al veel mee aan de slag gaat. Voor je wiki gaat het er om dat je het goed blijft aanvullen, je hebt in ieder geval een mooi begin gemaakt.

Je readme is goed opgevuld! Je zou nog kunnen toevoegen hoe iemand jouw app zelf kan installen en bekijken, kijk bijvoorbeeld naar grotere repo's van anderen op github voor inspiratie :)

Leg vooral nu de focus op het bouwen van je app, zodat je daar zo veel mogelijk feedback op kan krijgen. De rest kan je later nog toevoegen. Natuurlijk gaan prive omstandigheden voor dus push jezelf niet te veel ;)

Succes! 😊
